export const TEXT = {
  BRAND: 'دليلك',

  NAV: {
    LOGIN: 'دخول',
    REGISTER: 'إنشاء حساب',
    LOGOUT: 'تسجيل الخروج',
    SEARCH: 'بحث',
  },

  CATEGORIES: {
    ALL: 'الكل',
    VEGETABLES: 'خضاري',
    POULTRY: 'فرارجي',
    BUTCHERS: 'جزارين',
    HERBS: 'عطارين',
    GROCERY: 'بقاله',
    RESTAURANTS: 'مطاعم',
  },

  COVER: {
    HEADLINE: 'دوّر',
    SUB1: 'عايز تروح اي مكان؟',
    SUB2: 'هتروح بسهوله',
  },

  FILTERS: {
    CONSERVATIVE: 'المحافظه',
    AREA: 'منطقه',
    HAY: 'الحي',
    CATEGORY: 'التصنيفات',
    RATE: 'التقييم',
    RESET: 'مسح الكل',
    SELECT: 'اختر',
  },

  CARD: {
    ADDRESS: 'عنوان',
    LANDMARK: 'علامه مميزه',
    TYPE: 'النوع',
    RATE: 'التقييم',
    LOCATION: 'لوكيشين',
    NOT_FOUND: 'اسف...المكان ده لسه مش موجود',
  },

  AUTH: {
    LOGIN_TITLE: 'تسجيل الدخول',
    LOGIN_SUBTITLE: 'مرحباً بعودتك',
    REGISTER_TITLE: 'إنشاء حساب',
    REGISTER_SUBTITLE: 'انضم إلينا — مجاناً',
    ADMIN_TITLE: 'دخول الأدمن',
    EMAIL: 'البريد الإلكتروني',
    PASSWORD: 'كلمة المرور',
    SIGN_IN: 'تسجيل الدخول',
    SIGN_UP: 'إنشاء الحساب',
    SIGN_IN_GOOGLE: 'الدخول بحساب Google',
    SIGN_UP_GOOGLE: 'التسجيل بحساب Google',
    LOADING_IN: 'جاري الدخول...',
    LOADING_UP: 'جاري إنشاء الحساب...',
    OR_EMAIL_IN: 'أو سجل الدخول بالبريد',
    OR_EMAIL_UP: 'أو سجل بالبريد',
    NO_ACCOUNT: 'ليس لديك حساب؟',
    HAVE_ACCOUNT: 'لديك حساب بالفعل؟',
    CREATE_ONE: 'أنشئ حساباً',
    SIGN_IN_LINK: 'سجل الدخول',
    ADMIN_LINK: 'دخول الأدمن',
  },

  ADMIN: {
    ALL_SHOPS: 'كل المحلات',
    EDIT_SHOP: 'تعديل محل',
    ADD_SHOP: 'إضافة محل',
    MANAGE_USERS: 'إدارة المستخدمين',
    DELETE: 'حذف',
    UPDATE: 'تحديث',
    SEARCH: 'بحث',
    NAME: 'الاسم',
    ROLE: 'الدور',
    SUBMIT: 'حفظ',
    NO_SHOPS: 'لا توجد محلات',
  },

  COMMON: {
    LOADING: 'جاري التحميل...',
    ERROR: 'حدث خطأ',
    SAVE: 'حفظ',
    SAVING: 'جاري الحفظ...',
    SAVED: 'تم الحفظ',
    CANCEL: 'إلغاء',
  },

  PROFILE: {
    TITLE: 'الملف الشخصي',
    MENU_PROFILE: 'الملف الشخصي',
    MENU_LOGOUT: 'تسجيل الخروج',
    SECTION_ACCOUNT: 'الحساب',
    SECTION_CONTACT: 'التواصل',
    SECTION_ADDRESS: 'العنوان',
    SECTION_LOCATION: 'الموقع',
    SECTION_NOTES: 'ملاحظات',
    NAME: 'الاسم',
    NAME_PLACEHOLDER: 'اسمك بالكامل',
    PHONE: 'رقم الهاتف',
    PHONE_PLACEHOLDER: '01xxxxxxxxx',
    STREET: 'الشارع',
    STREET_PLACEHOLDER: 'اسم الشارع ورقمه',
    BUILDING: 'العمارة / الشقة',
    BUILDING_PLACEHOLDER: 'رقم العمارة والدور',
    AREA: 'المنطقة',
    AREA_PLACEHOLDER: 'الحي أو المنطقة',
    CONSERVATIVE: 'المحافظة',
    CONSERVATIVE_PLACEHOLDER: 'القاهرة، الجيزة...',
    LOCATION_URL: 'رابط الموقع',
    LOCATION_URL_PLACEHOLDER: 'رابط Google Maps',
    NOTES: 'ملاحظات إضافية',
    NOTES_PLACEHOLDER: 'أي تفاصيل تساعد في الوصول إليك',
    EMAIL_READONLY: 'البريد الإلكتروني (لا يمكن تغييره)',
    SUMMARY_HELLO: 'أهلاً',
    SUMMARY_NO_NAME: 'مستخدم',
    SUMMARY_HINT: 'أكمل بياناتك ليسهل الوصول إليك',
  },
};
